easy-bake:
  output: lib
  join: easy-bake.js
  files:
    - src/easy-bake_core.coffee
    - src/easy-bake_utils.coffee
    - src/easy-bake_commands.coffee

lib:
  output: lib/test_runners
  directories:
    - src/test_runners


tests:
  output: ./build
  bare: true
  directories:
    - test/easy-bake_core
  options:
    test:
      command: nodeunit
    files:
      - '**/*.js'
