library:
  output: '{root}'
  join: easy-bake.js
  files:
    - src/easy-bake_core.coffee
    - src/easy-bake_utils.coffee

lib_commands:
  join: easy-bake-commands.js
  output: lib
  files:
    - src/commands/queue.coffee
    - src/commands/commands.coffee

lib_test_runners:
  output: lib/test_runners
  directories:
    - src/test_runners

tests:
  output: ./build
  bare: true
  directories:
    - test/easy-bake_core
  options:
    test:
      command: nodeunit
      files:
        - '**/*.js'
