// Generated by CoffeeScript 1.3.3
(function() {
  var timeLog;

  timeLog = function(message) {
    return console.log("" + ((new Date).toLocaleTimeString()) + " - " + message);
  };

  String.prototype.startsWith = function(start) {
    return this.indexOf(start) === 0;
  };

}).call(this);
