// Generated by CoffeeScript 1.6.3
(function() {
  var Core, CoreHelpers;

  Core = (function() {
    function Core() {}

    return Core;

  })();

  CoreHelpers = (function() {
    function CoreHelpers() {}

    return CoreHelpers;

  })();

}).call(this);
